Feat/product page
laSinteZ/fake-burrberry-frontend pull request #1
Opened 2017-07-31 22:56 UTC by laSinteZ

2017-08-01 09:32 UTC, evgenyrodionov commented
https://rawgit.com/laSinteZ/fake-burrberry-frontend/feat/product-page/index.html

2017-08-01 11:27 UTC, evgenyrodionov commented
Отцентровал по названию товара — поехал логотип

![image](https://user-images.githubusercontent.com/775692/28819037-8ffd34ec-76b5-11e7-8457-a188ec704730.png)

2017-08-01 11:36 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28823540-bd0616be-76c6-11e7-8f99-72206586d6bc.png)
![image](https://user-images.githubusercontent.com/775692/28823550-c6d0e30e-76c6-11e7-9057-88ac1e2e5a22.png)
![image](https://user-images.githubusercontent.com/775692/28823560-ce4bfa92-76c6-11e7-9976-194dad02f968.png)
![image](https://user-images.githubusercontent.com/775692/28823570-dc3731bc-76c6-11e7-917b-c257cc384cf5.png)

2017-08-01 11:37 UTC, imevro requested changes
фикси дизайн

2017-08-01 23:21 UTC, laSinteZ commented
Fixed design:
- Replaced all borders with box-shadow: inset, so it fits grid
- Customized line-heights, so it looks like in zepplin
- Changed text-rendering to anti-alised (thanks to Georgy who told to do so yesterdays, looks better now)

2017-08-01 23:33 UTC, laSinteZ commented
Sorry for review addition/removal, I've needed to implement an important feature - favicon
![screen shot 2017-08-02 at 2 32 48 am](https://user-images.githubusercontent.com/10958990/28851420-e6dd5d1c-772a-11e7-914a-ce4ab08665a8.png)

2017-08-02 08:30 UTC, laSinteZ commented
**Fixed fix:**
- Fallback to native borders instead of `box-shadow`

2017-08-02 10:12 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28869065-3691e09a-7784-11e7-95e5-ae2c0fc5aad7.png)
![image](https://user-images.githubusercontent.com/775692/28869075-3ea1658a-7784-11e7-8682-358a301f725b.png)
![image](https://user-images.githubusercontent.com/775692/28869089-483f9d78-7784-11e7-8cc9-208362cae6f9.png)

бтв смени фавикон на нормальный

2017-08-02 10:14 UTC, imevro requested changes
↑

2017-08-02 15:23 UTC, laSinteZ commented
Отличия от макета (макет на 18-00 мск):
0. В "Descripton" текст едет на полшишечки, если уравнивать с шиппинг энд ретурн: отступ в цеплине у дескрипшн 31пх, наверное поэтому, а так хз.
1. "Shipping and return" - текст немного плывет вниз (на пиксель-полпикселя), но код как в цеплине и высота нужная. Какие-то проблемы с лайн хайтом.
2. В футере обе кнопки, и "шиппинг кантри раша" и "Language English" имеют по 16пх лайн хайт, в то время как в макете у "лангуаг енглиш" 14пх. Если макет не изменится, то продолжит расходиться, если изменится - будет всё заелись

2017-08-02 17:58 UTC, evgenyrodionov commented
Красавчик

2017-08-02 18:00 UTC, imevro requested changes
в целом норм

2017-08-02 18:00 UTC, evgenyrodionov commented on index.html
> +      <button class="product-controls-button button-dark">Select a size</button>
где type

2017-08-02 18:00 UTC, evgenyrodionov commented on index.html
> +      <div class="product-info-middle">
зачем див

2017-08-02 18:00 UTC, evgenyrodionov commented on index.html
> +    <div class="product-header">
зачем див

2017-08-02 18:00 UTC, evgenyrodionov commented on index.html
> +    <div class="content-divider"></div>
hr есть

2017-08-02 18:00 UTC, evgenyrodionov commented on index.html
> +        <div class="product-description-item-header"><h2 class="product-description-item-header-title">Shipping &amp; returns</h2><img src="img/triangle.svg" class="triangle"></div>
это кнопка раз
засунь пикчу в цсс два

2017-08-03 08:00 UTC, laSinteZ commented
1. div.product-header  убрал
2. div.product-info-middle убрал
3. переправил div на hr
4. кнопкам проставил type
5. засунул в кнопку, завёл класс Icon-triangle и is-reversed, чтобы было классно.

Помимо этого: Внёс NEED SIZE HELP в <h2>, потому что так в макете а я только увидел

2017-08-03 11:48 UTC, imevro requested changes

2017-08-03 11:48 UTC, evgenyrodionov commented on css/style.css
> +i.is-reversed{
нахуй i?

2017-08-03 11:48 UTC, evgenyrodionov commented on index.html
> +        <button class="product-info-bottom-button-colour is-active" type="button"></button>
где контент внутри? для скринридеров

2017-08-03 11:48 UTC, evgenyrodionov commented on index.html
> +      <button class="product-controls-button button-text-only" type="button"><h2 class="button-text-only-title">Need size help?</h2></button>
в смысле зачем тут h2

2017-08-03 11:48 UTC, evgenyrodionov commented on index.html
> +        <button class="product-description-item-button" type="button"><h2 class="product-description-item-button-title">Description</h2><i class="icon-triangle is-reversed"></i></button>
убирай <i>, это вообще костыльный способ работы с ассетами

2017-08-03 13:55 UTC, laSinteZ commented
Вроде пофиксил все замечания. 
К завтра запилю планшетную версию.

2017-08-03 20:13 UTC, imevro requested changes

2017-08-03 20:13 UTC, evgenyrodionov commented on index.html
> +        <button class="product-info-bottom-button-colour is-active" type="button" aria-label="Black colour"></button>
в тег

2017-08-04 08:41 UTC, laSinteZ commented
Ну прими пуллреквест, я уже вроде всё, что смог увидеть, исправил, **позязя**

2017-08-04 09:49 UTC, evgenyrodionov commented
Проверка судя по всему была на 12 утра, поэтому проверю в 3

2017-08-04 12:49 UTC, imevro requested changes

2017-08-04 12:49 UTC, evgenyrodionov commented on css/style.css
> +  line-height: 0px;
нельзя, что за костыль? зачем?

2017-08-04 12:49 UTC, evgenyrodionov commented on index.html
> +  <header class="header"><a href="#" class="header-logo"><img src="img/logo.svg" class="logo"></a></header>
у тебя энтер сломался? зачем ты 3 тега в одну строку нахуярил?

2017-08-04 18:21 UTC, imevro approved these changes

2017-08-05 13:35 UTC, laSinteZ commented
Отличия от макета:
1. Надпись Delivery осталась названной Shipping & Returns, как в мобильном макете. Также эта надпись имеет Line-height 20px, как и в мобильной версии для консистенси, поэтому текст едет вниз на 1 пиксель. (Спрашивал в чате)
2. В мобильном макете аккордеон Shipping & Returns раскрыт и в нём только текст, как в планшетной версии, но без картинки с подарком. (Спрашивал в чате)
3. Various ездинги текста по горизонтали на 1 пиксель. (Как в старые добрые)

2017-08-05 16:49 UTC, laSinteZ commented
Апдейт: бомбанул **цсскомб** с пресетом _zen_, чтобы жить было приятнее

2017-08-05 18:20 UTC, imevro requested changes

2017-08-05 18:20 UTC, evgenyrodionov commented on index.html
> +            <a href="#">Terms &amp; Conditions</a>
в нав

2017-08-05 18:20 UTC, evgenyrodionov commented on css/style.css
> +.footer-navigation h4 {
нельзя вешать на теги, ты чё

2017-08-05 19:46 UTC, laSinteZ commented
Убрал стили из тегов (а)
Запихал ссылки в нав (б)
Добавил кейвордов, дескрипшн и ещё чего-то в мету (в)
Ещё немного проверил семантику и обернул основной контент в `<main>` вместо просто дива (г)

2017-08-05 21:07 UTC, laSinteZ commented
Слона-то я и не заметил. Починил сломанный футер, спасибо Витале.

2017-08-06 08:57 UTC, imevro approved these changes

2017-08-06 09:00 UTC, merged

2017-08-06 09:00 UTC, evgenyrodionov commented
Гит чекаут мастер, гит пулл ориджин мастер --ребейз, новые бранчи от нового мастера