Mobile/Tablet in react
laSinteZ/fake-burrberry-frontend pull request #2
Opened 2017-08-11 15:09 UTC by laSinteZ

Отличия от макета:
Аккордеоны пока не работают, всё остальное вроде ок

2017-08-11 19:02 UTC, imevro requested changes
читай телеграф, оттуда собрал много ошибок

2017-08-11 19:02 UTC, evgenyrodionov commented on .eslintrc.json
> +        "browser": true,
что с отступами, камон

2017-08-12 10:13 UTC, imevro requested changes

2017-08-12 10:13 UTC, evgenyrodionov commented on src/App.js
> +class App extends Component {
зачем тут класс

2017-08-12 10:13 UTC, evgenyrodionov commented on src/Product/Accordions/Shipping.js
> +              <h4>Free Next Day Delivery</h4>
я уже говорил — ЭТИ ДАННЫЕ СТАТИЧНЫ

2017-08-12 12:32 UTC, laSinteZ commented
Вроде всё поправил, но внушил целый 1 коммит с декстоповскими изменениями :(

2017-08-12 18:20 UTC, imevro requested changes

2017-08-12 18:20 UTC, evgenyrodionov commented on src/Product/Accordions/Shipping.js
> +  & + ${Subtitle} {
что это за хуйня

2017-08-12 18:20 UTC, evgenyrodionov commented on src/common/responsive.js
> +export const Desktop = ({ children }) =>
телеграф

2017-08-12 18:21 UTC, evgenyrodionov commented on src/common/responsive.js
> +export const Desktop = ({ children }) =>
и поч файл с маленькой буквы если это компоненты

2017-08-13 12:20 UTC, merged