Desktop react page
laSinteZ/fake-burrberry-frontend pull request #3
Opened 2017-08-12 12:31 UTC by laSinteZ

2017-08-12 14:46 UTC, laSinteZ commented
Отличия от макета:
![screen shot 2017-08-12 at 5 40 56 pm](https://user-images.githubusercontent.com/10958990/29241587-6e35c1d4-7f85-11e7-9eda-968f82fabd4a.png)
Потому что картинка в целине имеет чуть большую высоту, а я переиспользую старую, поэтому весь имеет меньшую высоту => центруется чуть в другом месте.

Line-height у Дескрипшн и Деливири 20 пикселей (в макете 19), потому что в планшете-телефоне 20.

В "We recommend" старые пикчи и текст.

2017-08-12 19:09 UTC, evgenyrodionov commented
нахуя ты в мастер вешаешь

2017-08-12 19:15 UTC, imevro requested changes

2017-08-12 19:15 UTC, evgenyrodionov commented on src/App.js
> +let productTitle = "Long Cotton Gabardine Car Coat Coat Coat Coat Coat"
зачем леты

2017-08-12 19:15 UTC, evgenyrodionov commented on src/App.js
> +let productImages = [{src: "img/product-1.jpg", alt: "Long Cotton Gabardine Car Coat"}, {src: "img/product-2.jpg", alt: "Long Cotton Gabardine Car Coat"}, {src: "img/product-3.jpg", alt: "Long Cotton
бля поставь преттир и разверни это нормально, зачем в одну строку писать

2017-08-12 19:15 UTC, evgenyrodionov commented on src/App.js
> +          <title>Long Cotton Gabardine Car Coat | Men - Burberry</title>
а тут почему не используешь свой продакттайтл

2017-08-12 19:15 UTC, evgenyrodionov commented on src/Product/Gallery.js
> +  > *:nth-child(1) {
`*` — уебищный селектор

2017-08-12 19:15 UTC, evgenyrodionov commented on src/Product/Gallery.js
> +          <Image src={props.images[1].src} alt={props.images[1].alt} />
используй метод map у массива

2017-08-12 19:15 UTC, evgenyrodionov commented on src/Product/InfoPanel/Price.js
> +      <Medium>
медиум что? этот блок отображается только на медиуме? из дизайна я знаю что это не так

2017-08-12 19:15 UTC, evgenyrodionov commented on src/Product/InfoPanel/index.js
> +            <Price id="39428531" price={110000} currency="RUB" />
Price id?

2017-08-12 19:15 UTC, evgenyrodionov commented on src/Product/InfoPanel/index.js
> +      <Large>
очень тупая система где тебе нужно держать два лэйаута. реакт-респонсив нужен для различающихся частей, а не всей страницы

2017-08-12 19:15 UTC, evgenyrodionov commented on src/Product/index.js
> +border: none;
что с отступами

2017-08-12 19:15 UTC, evgenyrodionov commented on src/Product/index.js
> +            <Title>{props.title}</Title>
и тут

2017-08-13 10:41 UTC, imevro requested changes
исправишь — напиши в личку телеграма

2017-08-13 10:41 UTC, evgenyrodionov commented on src/common/Breakpoints.js
> +export const Md = ({ children }) =>
ToMd мб

2017-08-13 12:20 UTC, merged