Products page and React-Router
laSinteZ/fake-burrberry-frontend pull request #5
Opened 2017-08-18 13:28 UTC by laSinteZ

2017-08-18 13:32 UTC, laSinteZ commented
Отличия от макета:

1. Немного неидеальная стрелочка вниз у дропдаунов (1пх)
2. Немного неидеальный гамбургер
3. Кнопка  View x More - в цеплине опять внутренние бордеры, поэтому моя с внутренними отступами 1-2 рем отличается
4. У активной кнопки "Men" в цеплине отступ до полосы нижней 15пх, а у меня 1rem.
5. Обе "категории" товаров одни и те же (Рендерятся из массива, если надо, то сделаю супер-правильный массив).

2017-08-18 15:56 UTC, laSinteZ commented
https://build-nylxmwzhgi.now.sh

2017-08-18 17:38 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/29470413-0985a7a2-8455-11e7-89d0-9f1ac5130205.png)

?
![image](https://user-images.githubusercontent.com/775692/29470428-15e7b18e-8455-11e7-8a92-08ea614e1d98.png)

![image](https://user-images.githubusercontent.com/775692/29470455-34b07ed4-8455-11e7-8dd1-7415279ef9b0.png)

2017-08-18 17:38 UTC, evgenyrodionov commented
Разберись с GBP, откуда оно взялось, если должно быть £?

2017-08-18 17:40 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/29470501-5f03bd9a-8455-11e7-9521-5621e44b82b3.png)

Не понял что с сеткой
![image](https://user-images.githubusercontent.com/775692/29470512-6c08d110-8455-11e7-94b6-70bc502b6aa9.png)

![image](https://user-images.githubusercontent.com/775692/29470531-7abcd030-8455-11e7-96a0-6783a72ecbf8.png)

2017-08-18 18:49 UTC, laSinteZ commented
Починил почти всё. (предыдущие отличия от макета в силе)

![screen shot 2017-08-18 at 9 44 22 pm](https://user-images.githubusercontent.com/10958990/29472946-705a3b74-845e-11e7-8f59-5d02aef29587.png)
На десктопе в макете отступы то 48, то 56, на планшете 49, у меня _везде_ 48, поэтому вот такое.

На десктопе в макете картинки не попали в сетку. Договорились делать width:100%.

В карточках из-за подчёркивания может чуть-чуть ехать цена-цвета.

Без смены локали с РУ все единицы измерения денег после.

https://build-oqbjdvvhho.now.sh/

2017-08-18 22:28 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/29479842-2df94440-847d-11e7-9bcf-353c6c6abe55.png)

![image](https://user-images.githubusercontent.com/775692/29479876-60699722-847d-11e7-8d59-f4840b200038.png)
![image](https://user-images.githubusercontent.com/775692/29479888-700692e8-847d-11e7-9319-668a57a1b294.png)

2017-08-18 22:31 UTC, imevro requested changes

2017-08-18 22:31 UTC, evgenyrodionov commented on src/App.jsx
> +            content={
что это делает тут? почему это не на странице товара?

2017-08-18 22:31 UTC, evgenyrodionov commented on src/App.jsx
> +              render={props => <Product {...props} title={productTitle} images={productImages} />}
красава, хитро, но про роуты почитай телеграф

2017-08-18 22:31 UTC, evgenyrodionov commented on src/Products/Header.jsx
> +    props.isMain &&
выглядит как костыль

2017-08-19 00:25 UTC, laSinteZ commented
https://build-yfyllkqhvl.now.sh <- все топ пацаны там

Отличия от макета: всё как и раньше +
Высота заголовка в мобильной версии не 19, а 20. Потому что какой 19.

2017-08-19 10:42 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/29485948-277eee14-84e4-11e7-856a-15a4eb261fa8.png)
![image](https://user-images.githubusercontent.com/775692/29485954-4ba023bc-84e4-11e7-82c0-c3cb3ca2b1e5.png)

2017-08-19 10:43 UTC, evgenyrodionov commented
> 3 colours
у тебя не ссылкой, а должно быть

2017-08-19 10:44 UTC, evgenyrodionov commented
Поправь карточки на странице товара

![image](https://user-images.githubusercontent.com/775692/29485970-81449a70-84e4-11e7-80a8-8905b801bf6b.png)

2017-08-19 10:48 UTC, imevro requested changes
↑

2017-08-19 13:29 UTC, laSinteZ commented
https://build-mrywedwepp.now.sh

Known issue: При переходе на сайт нас редиректит на /men. При нажатии на логотип мы попадаем на /, но на men не редиректит и получается немного голая страница. Fun.

2017-08-19 14:21 UTC, laSinteZ commented
https://build-gddkuohxek.now.sh

Refine, bye!
Роутинг починен.
Кновн ишью: без рефайн-бай выглядит ублюдско на xs.

2017-08-19 15:35 UTC, laSinteZ commented
https://build-wcuoqjvlln.now.sh

Refine, bye!
Роутинг починен.
Кновн ишью: без рефайн-бай выглядит ублюдско на xs.

2017-08-19 19:38 UTC, imevro requested changes

2017-08-19 19:38 UTC, evgenyrodionov commented on src/common/Card.jsx
> +export default function Card(props) {
коммон/кард? ок, вопрос — это карточка чего? как это понять? я зашёл в проект, увидел коммон/кард, дальше что? как ты будешь один коммонкард отличать от другого?

2017-08-19 19:38 UTC, evgenyrodionov commented on src/common/Card.jsx
> +      <RouteLink to={props.link}>
to={link}? камон

2017-08-19 19:38 UTC, evgenyrodionov commented on src/common/Card.jsx
> +            defaultMessage={`{colourNumber, number} {colourNumber, plural,
вынеси куда-нибудь в константу за пределы рендера, некрасиво же

2017-08-19 20:27 UTC, laSinteZ commented
Жизнь диплоям, ауе

2017-08-19 20:28 UTC, laSinteZ commented
https://build-damopadztx.now.sh

Жизнь деплоям. Вроде починил всё.

2017-08-19 21:31 UTC, laSinteZ commented
https://build-jtftotsmuv.now.sh

Вроде починил всё. Даже цену на странице товара сделал, как в макете - жирной на десктопе. И текст от страного сердечка отодвинул.

2017-08-20 09:07 UTC, imevro approved these changes

2017-08-20 09:07 UTC, evgenyrodionov commented on src/Product/InfoPanel/index.jsx
> +      <PriceArticle id={39428531} price={110000} currency="RUB" />
не нужно айди передавать таким большим числом, это ненадежно — джс не дружит с бигинтом

2017-08-20 09:08 UTC, merged