Now + Travis = love
laSinteZ/fake-burrberry-frontend pull request #6
Opened 2017-08-22 13:18 UTC by laSinteZ

http://vbikbaev-burberry-fake-shop-for-study-dev.now.sh

А если примешь пуллреквест (и всё сработает как надо) будет http://vbikbaev-burberry-fake-shop-for-study.now.sh после пуша в мастер

Всё, что не "master" деплоится в http://vbikbaev-burberry-fake-shop-for-study-dev.now.sh

Такие дела.

2017-08-22 14:26 UTC, laSinteZ commented
Сделал элегантнее.

2017-08-22 17:26 UTC, imevro requested changes

2017-08-22 17:26 UTC, evgenyrodionov commented on .travis.yml
> +    - URL_DEV: vbikbaev-burberry-fake-shop-for-study-dev
можешь это передавать в настройках трависа?

2017-08-22 17:28 UTC, evgenyrodionov commented
И я кстати не понял, а где сам деплой-то? Билд вижу, альяс вижу, а деплой где?

2017-08-22 21:45 UTC, laSinteZ commented
Перенёс переменные в древес. Добавил скип клинап, протестил на ветке develop, добавив коммит, меняющий главную для ясности (и удалил её уже, лол), всё охеренно работает. с пруфами. https://travis-ci.org/laSinteZ/fake-burberry-frontend/builds/267359680

2017-08-23 09:41 UTC, imevro approved these changes

2017-08-23 09:41 UTC, merged