Colours buttons and Sizes buttons
laSinteZ/fake-burrberry-frontend pull request #8
Opened 2017-08-31 13:08 UTC by laSinteZ

Вроде бы работают. Заодно рефакторнул по гайдам другие штуки.

2017-08-31 13:30 UTC, laSinteZ commented
Понемногу пилим. https://build-iqmjmebbyd.now.sh

2017-08-31 17:52 UTC, evgenyrodionov commented
cursor pointer

2017-08-31 17:53 UTC, evgenyrodionov commented
Переделай тут на паддинги внутренние, а то не кликается по пустому пространству

![image](https://user-images.githubusercontent.com/775692/29937490-70f70f78-8e8e-11e7-9f6e-4f6cf87be5f9.png)

2017-08-31 17:55 UTC, imevro requested changes

2017-08-31 17:55 UTC, evgenyrodionov commented on src/Product/Gallery.jsx
> +        {props.images.slice(1, 4).map(img => (
слайс мутирует, пропы и стейт нельзя мутировать

2017-08-31 17:55 UTC, evgenyrodionov commented on src/Product/Gallery.jsx
> +        {props.images.slice(1, 4).map(img => (
скопируй массив

2017-08-31 17:55 UTC, evgenyrodionov commented on src/Product/InfoPanel/ButtonSize.jsx
> +      {`${props.value}`}
зачем тут выполнять джс

2017-09-01 14:20 UTC, laSinteZ commented
Починил всё, что в ПРе + добавил дропдаун селекторы для Shipping Country, colour (в мобилке), Language.

https://build-lwdssyfwpb.now.sh

2017-09-01 17:14 UTC, imevro requested changes

2017-09-01 17:14 UTC, evgenyrodionov commented on src/Footer/Selector.jsx
> +    & + & {
бля что ты делаешь

2017-09-01 17:14 UTC, evgenyrodionov commented on src/Footer/Selector.jsx
> +    & + & {
что это за тупые селекторы

2017-09-01 17:14 UTC, evgenyrodionov commented on src/Product/InfoPanel/index.jsx
> +  color: Transparent;
лол почему с большой

2017-09-01 17:14 UTC, evgenyrodionov commented on src/Product/InfoPanel/index.jsx
> +  margin-bottom: -3rem;
зачем отрицательный марджин

2017-09-01 18:57 UTC, laSinteZ commented
https://build-itafybpwzc.now.sh

2017-09-02 09:30 UTC, imevro requested changes

2017-09-02 09:30 UTC, evgenyrodionov commented on src/Product/InfoPanel/index.jsx
> +                      onClick={() => {
можно опустить {}

2017-09-02 09:30 UTC, evgenyrodionov commented on src/Product/InfoPanel/index.jsx
> +                      onClick={() => {
в смысле `onClick={() => this...}`

2017-09-02 14:57 UTC, laSinteZ commented
Не стал лить на now, потому что изменения только в коде и на отображение не влияют.

2017-09-02 18:05 UTC, imevro approved these changes

2017-09-26 20:20 UTC, merged