Filters implementation
laSinteZ/fake-burrberry-frontend pull request #9
Opened 2017-09-02 14:58 UTC by laSinteZ

Заимплементил выпадающие фильтры, с клик-аутсайдом, всё как надо. Не рендерю их массивом потом что пока что не уверен, как будет выглядеть API.

2017-09-02 19:03 UTC, imevro requested changes

2017-09-02 19:03 UTC, evgenyrodionov commented on src/Products/Filter.jsx
> +      document.removeEventListener('click', this.handleOutsideClick, false);
достаточно при маунте повесить

2017-09-02 22:31 UTC, laSinteZ commented
Перевесил на DidMount, свою бракованную логику поменял на подсмотренную у mlshv, с сохранением текущего открытого фильтра в родителе.

Алсо, починил всякую мелочевку.
Анимация _квадратичная_, лучшая в мире.

https://build-tdvzgtbidu.now.sh

2017-09-03 12:39 UTC, imevro requested changes

2017-09-03 12:39 UTC, evgenyrodionov commented on src/App.jsx
> +    isHamburgerOpened: false,
меняем ГАМБУРГЕР на обычный текст Menu, что дальше?

2017-09-03 12:39 UTC, evgenyrodionov commented on src/Hamburger/index.jsx
> +    subsectionNumber: 0,
не намбер, а индекс

2017-09-03 12:39 UTC, evgenyrodionov commented on src/Products/Filter.jsx
> +    if (on || on !== this.state.isOpened) {
читай замечание у того у кого спиздил :)

2017-09-03 12:39 UTC, evgenyrodionov commented on src/Products/Filters.jsx
> +    if (toggledOn) {
тут можно и в тернарник сделать

2017-09-03 12:39 UTC, evgenyrodionov commented on src/Products/Filters.jsx
> +              this.state.activeFilterName !== undefined && this.state.activeFilterName !== 'Sort by price'
лейбл не очень надежен, лучше заведи ключ типа `sort-price`

2017-09-06 21:48 UTC, laSinteZ commented on src/Products/Filter.jsx
> +    if (on || on !== this.state.isOpened) {
Читал like 40 раз, там вроде речь шла о сетстейте функцией, а не объектом, вроде всё так делаю.

2017-09-07 09:08 UTC, evgenyrodionov commented
Как исправишь — повесишь

2017-09-08 08:25 UTC, laSinteZ commented
Переписал логику, наконец-то перестал хранить id открытого фильтра ибо зачем оно нам надо.

https://build-vjvrhwvfaj.now.sh

2017-09-08 17:41 UTC, imevro requested changes

2017-09-08 17:41 UTC, evgenyrodionov commented on src/App.jsx
> +            <div>
зачем этот див

2017-09-08 17:41 UTC, evgenyrodionov commented on src/App.jsx
> +        <div>
зачем этот див

2017-09-08 17:41 UTC, evgenyrodionov commented on src/Hamburger/Subsection.jsx
> +import React from 'react';
опять напоминаю про нейминг — что за гамбургер?

2017-09-08 17:41 UTC, evgenyrodionov commented on src/Header/index.jsx
> +          <Hamburger onClick={props.handleHamburgerClick} />
бля ну опять вот

2017-09-09 10:58 UTC, imevro requested changes

2017-09-09 10:58 UTC, evgenyrodionov commented on src/Header/index.jsx
> +          <Hamburger onClick={props.onHamburgerClick} />
бля ну опять гамбургер, сколько можно

2017-09-11 09:58 UTC, imevro approved these changes

2017-09-11 09:58 UTC, merged